export const API_KEY = "3898867ebc97917c67c0d9841df34dce";
export const FETCH_MOVIES = "FETCH_MOVIES";
export const REQUEST_MOVIES = "REQUEST_MOVIES";
export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";
export const FETCH_MOVIE_DETAILS = "FETCH_MOVIE_DETAILS";
export const REQUEST_MOVIE_DETAILS = "REQUEST_MOVIE_DETAILS";
