export const API_KEY = "3898867ebc97917c67c0d9841df34dce";

export const FETCH_MOVIES = "FETCH_MOVIES";
export const REQUEST_MOVIES = "REQUEST_MOVIES";
export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";
export const FETCH_MOVIE_DETAILS = "FETCH_MOVIE_DETAILS";
export const REQUEST_MOVIE_DETAILS = "REQUEST_MOVIE_DETAILS";
export const FETCH_GENRES = "FETCH_GENRES";
export const FETCH_SIMILARS = "FETCH_SIMILARS";
export const CLEAR_BEST_MOVIES = "CLEAR_BEST_MOVIES";
export const REQUEST_SEARCH = "REQUEST_SEARCH";
export const FETCH_SEARCH = "FETCH_SEARCH";
export const CLEAR_SEARCHED_MOVIES = "CLEAR_SEARCHED_MOVIES";
export const RECEIVE_TOTAL_PAGES = "RECEIVE_TOTAL_PAGES";
